### PR TITLE
#16 use `unzip` on Windows

### PR DESCRIPTION
**Pull request by CSJCampbell**
`untar` operation is not supported on Windows. Create modality for alternative platform.

### CODE REVIEW

**Comment by gaborcsardi** [comment]
This will only work if the package is a zip file. It might be a zip file, it might be a tar.gz file. I think you need to decide from the file extension, which can be '.tar.gz', '.tgz' (on macOS) or '.zip'.

**Comment by CSJCampbell** [comment]
I think @ManuelaAlmeida's pull request may fix this issue actually. I had not spotted it earlier.

**Comment by gaborcsardi** [comment]
Yeah, looks like it.

**Comment by gaborcsardi** [comment]
But I am not sure about the other thing it does.

**Comment by CSJCampbell** [comment]
change needs more development

**Pull request closed without merging**
